server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/leecx
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  freemarker:
    # 设置 ftl 文件路径
    # 关闭缓存，及时刷新，上线环境需要改为 true
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path: classpath:/templates
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
#    prefix: classpath:/templates 这句抽筋了
  # 配置 i18n 资源文件，供 thymeleaf 读取
  messages:
    basename: i18n/messages
    cache-seconds: 3600
    encoding: UTF-8
  # Redis 数据库索引
  redis:
    database: 0
    host: 192.168.75.128
    port: 6379
    password:
    pool:
      max-active: 1000
      max-wait: -1
      max-idle: 10
      min-idle: 2
    timeout: 0
logging:
  file: girl.log
  level: warn
mybatis:
    type-aliases-package: com.cier.girl.pojo
    mapper-locations: classpath:mappers/*.xml

mapper:
    mappers:
        - com.cier.girl.utils.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql


