server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dbgirl
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
#  freemarker:
#    # 设置 ftl 文件路径
#    # 关闭缓存，及时刷新，上线环境需要改为 true
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    request-context-attribute: request
#    suffix: .ftl
#    template-loader-path: classpath:/templates
  thymeleaf:
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
#    prefix: classpath:/templates 这句抽筋了
logging:
  file: girl.log
  level: error